language: node_js
node_js:
- '6'
- '6.1'
- '5.11'
before_install:
   - npm install -g istanbul
deploy:
  provider: npm
  api_key:
    secure: OmnfUnfOE5zpTN+emhzTjolpQ+bddMX/K1nX3Ur3EwPt1xB0a5i+Oqelk+//oNnoDnZ3klSc7ED9RFu5KtaOF+QFNPPR8KCQ+E+m0zSMFF5A0KbOnZVpEw16YqNm6JgRz9AZsomH58oxszoQ4seMuPNZy7Q0KLmo+B7X6GYKvXbwBDyNpQ2IdtmMidHV/xJ6WFs94buWhhuRixghufWyYNOYDnIvMum2XUfCXdXFGYrtNvsfvBGGWj99XyIakr7yAMHbseAI4XNUCaL6V0OBP8NF1AQP5diddEpm6EdqZaYtfyjHaE3RBHgAl4CnEXN2ESRqoirhvTVOO38Ff0DL0o/AlYMRnKj/ToDZIHFpIqHyWlROgr1aylaAK55FV4MmHAQJQOybi2+tNVq2Cwz958jPzmQXrFsL4Ta/Os6zbeSULzVaeuM8ZZkPO06FalIIU97xQeh/2Vnx3YrbF2y04lLLWs4j0z4iR250KArw3GL1tc7ri/3lYXpjdxh6Xs7F7lppWQ5i4RzgFBDQgcEvwPKZrj1B8ah0tolRuPKM/7CQz5qg7KWMWSdlSZTmk2d1sw0ueMEFDw2ERs6dpfHYvzmS6RRJTa2E7aayByTyCBgCjF0Hw2IfSWAPmunPxMuqibu/q3VqCcT2Egr1810dcAPYc4yF8yvdetmUojwUMFU=
  on:
      tags: true
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d8af9ef2ba8b5a8aaf55
    on_success: always
    on_failure: always
    on_start: never

after_success:
  - istanbul cover examples/stringfile.sh --report lcovonly -- -R spec
  - bash <(curl -s https://codecov.io/bash)
